package com.comvee.hospitalabbott.bean;

public enum BloodType {
    BLOOD_TYPE_SINGLE_ONE,BLOOD_TYPE_SIGNLE_TWO,BLOOD_TYPE_ONE_TIRUO,BLOOD_TYPE_ONE_RENCHEN,BLOOD_TYPE_TWO_TIRUO,BLOOD_TYPE_TWO_RENCEN
}
